### ISSUE TITLE
Font and Text Customization

### ISSUE THREAD

**Issue by Karabosithole** [Karabosithole/affirmation_generator#7]
- Allow users to change font style, size, and color for affirmations.

- Include a preview feature for text customization.

**Comment by NqobileMthombeni** [comment]
1. **Custom Font Implementation** : Introduced `CustomFontName` as the primary font for all affirmation text, enhancing readability and providing a cohesive look across the app.

2. **Theme Customization** : Added theme support with light and dark modes, enabling users to switch based on their preferences.
3. **Consistent Text Styling** : Standardized font size, weight, and color across screens for a unified user experience._

4. **New Feature**: Users can now "like" or "favorite" affirmations, which will save them for easy access later. This feature enhances personalization and encourages users to save affirmations that resonate with them.
